### ISSUE TITLE
[TASK] Setup Node JS boilerplate

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/unexpected-journey#1]
**Setup node js boilerplate**
We have to discuss best modern boilerplate for node js, which we can use.

**TODO list**
Criteria: support ES7, test on Jest (no Mocha / Jasmine), no TS, has some webpage already
- [ ] Discuss and find best suitable repo on github
- [ ] Ensure, that it runs ok
- [ ] Add to our repo

**Related story**
#4 

**Related subtasks**

**Additional information**
Add something more, if it required

**Comment by SirSerje** [comment]
I propose to use https://github.com/danielfsousa/express-rest-es2017-boilerplate and make some changes, sounds ok?
