### ISSUE TITLE
[TASK] Boilerplate features

### ISSUE THREAD

**Issue by SirSerje** [SirSerje/unexpected-journey#3]
**NOTE DONE YET**
For easy development, boilerplate should have some features on board.

**TODO list**
- [ ] ES7
- [ ] no TS
- [ ] (nice to have) test on Jest
- [ ] no Chai / Mocha / Jasmine (I don't like it)
- [ ] simple webpage on start
- [ ] nodemon / some server runner with fast reload

**Related story**
#4

**Related subtasks**

**Additional information**

**Comment by SirSerje** [comment]
Requires #6 in `develop`
